languageCode = "fr"
languageName = "French"
languageDirection = "ltr"
weight = 1

title = "Benjamin Falière"
copyright = "© 2025 Benjamin Falière"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
# description = "My awesome website"

[params.author]
name = "Benjamin Falière"
# image = "img/bf.jpg"
headline = "Des solutions pour votre système d'information"
# bio = "A little bit about you"
links = [
  { github = "https://github.com/BenjaminFlr" },
  { linkedin = "https://www.linkedin.com/in/benjamin-fali%C3%A8re-820a28174/" },
  { mastodon = "https://hostux.social/@BenjaminFaliere" },
  { telegram = "https://t.me/BenjaminFlr" },
  { bluesky = "https://bsky.app/profile/benjamin.faliere.com" },
  { discord = "https://discordapp.com/users/1072064544131776593" },
  { rss = "https://benjamin.faliere.com/index.xml"},
]
